# -*- coding: utf-8 -*-
# Copyright (C) 2024 Benjamin Thomas Schwertfeger
# GitHub: https://github.com/btschwertfeger
#
# Template workflow to build the project and publish
# the package to test PyPI.
#

name: PyPI Publish

on:
  workflow_call:
    secrets:
      API_TOKEN:
        required: true

permissions: read-all

jobs:
  publish-to-test-pypi:
    name: Publish Python distribution to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for OIDC publishing
    environment:
      name: testpypi
      url: https://test.pypi.org/p/genai-pod
    steps:
      - name: Download all the distributions
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish package distributions to Test PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # release/v1
        with:
          password: ${{ secrets.API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
